import Head from 'next/head'
import styles from '@/styles/mvp.module.scss'

export default function PageMVP() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.page_mvp}>
        <h2>MVP / index</h2>
      </main>
    </>
  )
}
